server:
  port : 8086
spring:
  application:
    name: ample16
  security:
    user:
      name: kaka
      password: 123456
#  redis:
#    port: 6379
#    host: 192.168.249.149
#    password: redis@kuaidi100
log-path: ${user.dir}
